---
language: go
go:
  - 1.11
env:
  - GO111MODULE=on
script:
  - (! go fmt ./... 2>&1 | read) || (echo "Code is not properly formatted, remember to use gofmt on all new changes." && exit 1)
  - go vet ./...
